version: "2"

services:
  blockchain:
    build: blockchain
    ports:
      - 8180:8180
  datastore-api:
    build: datastore-api
    ports:
      - 8280:8080
    volumes:
      - ./datastore-api/docker/deployments:/opt/jboss/wildfly/standalone/deployments
    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=dbh17
      - MYSQL_DATABASE=fima
    ports:
      - 3306:3306
  idp_implementor:
    build: idp-implementor
    ports:
      - 8380:8080
    links:
      - blockchain
  pdm_ui:
    build: pdm-ui
    links:
      - blockchain
      - datastore-api
    ports:
      - 3000:3000
      - 8080:8080
