version: "2"
services:
  datastore-api:
    build: datastore-api
    ports:
      - 8080:8080
    volumes:
      - ./datastore-api/docker/deployments:/opt/jboss/wildfly/standalone/deployments
    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=dbh17
      - MYSQL_DATABASE=fima
    ports:
      - 3306:3306