version: "3.2"

services:
  blockchain:
    build: blockchain
    image: ${IMAGE_REGISTRY}blockchain
    ports:
      - 8180:8180
      - 8545:8545
      - 8546:8546
  datastore-api:
    build: datastore-api
    image: ${IMAGE_REGISTRY}datastore-api
    ports:
      - 8280:8080
    volumes:
      - ./datastore-api/docker/deployments:/opt/jboss/wildfly/standalone/deployments
    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=dbh17
      - MYSQL_DATABASE=fima
    ports:
      - 3306:3306
  idp_implementor:
    build: idp-implementor
    image: ${IMAGE_REGISTRY}idp-implementor
    ports:
      - 8380:8080
    links:
      - blockchain
  pdm_ui:
    build: pdm-ui
    image: ${IMAGE_REGISTRY}pdm-ui
    links:
      - blockchain
      - datastore-api
    ports:
      - 3000:3000
      - 8080:8080
